// Generated by CoffeeScript 1.12.7
(function() {
  var a, age, b, count, key, name, names, ref, result, student, students, value;

  console.log("Welcome to coffeeScript World.");

  name = "Saloni Sawarkar";

  age = 20;

  console.log(name + " " + age);

  a = 21;

  b = "21";

  result = 21 === '21';

  console.log(result);

  console.log("starting loop");

  count = 0;

  while (count < 10) {
    console.log("Countno " + count);
    count++;
  }

  ref = {
    name: "Mom",
    age: 24,
    phone: 9848022338
  };
  for (key in ref) {
    value = ref[key];
    console.log(key + "::" + value);
  }

  students = [
    {
      name: "Mom",
      age: 24,
      phone: 9848022338
    }, {
      name: "Ram",
      age: 25,
      phone: 9800000000
    }, {
      name: "Saloni",
      age: 20,
      phone: 9800000900
    }
  ];

  names = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = students.length; i < len; i++) {
      student = students[i];
      results.push(student.name);
    }
    return results;
  })();

  console.log(names);


  /*
  my_function = ->
     name = "John"
     alert "Hello"+name
   */


  /*
  These are the multi line comments in CoffeeScript
  We can write as many number of lines as we want
  within the pair of triple hash tags.
   */

}).call(this);
